default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'postgres' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'test_postgres' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'postgres' %>
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
